'use strict';

const Controller = require('egg').Controller;

class HomeController extends Controller {
  async index() {
    const { ctx } = this;
    await ctx.render('meun.html',{
      itemlist:[
        {
          id:"1",
          url:'',
          word:'首页'
        },
        {
          id:"2",
          url:'',
          word:'手册'
        },
        {
          id:"3",
          url:'',
          word:'问答'
        },
        {
          id:"4",
          url:'',
          word:'我的'
        },
      ]
    })
  }
  async header() {
    await this.ctx.render("header.html",{
      logo:'晓舟报告',
      team:'团队介绍',
      xiaozhou:'晓舟报告',
      itemlist:[
        {
          id:"1",
          url:'',
          word:'首页'
        },
        {
          id:"2",
          url:'',
          word:'手册'
        },
        {
          id:"3",
          url:'',
          word:'问答'
        },
        {
          id:"4",
          url:'',
          word:'我的'
        },
      ],
      booklist:[
        {
          url:'../public/img/2.jpg',
          name:'前段开发电子书',
          outline:'午时快到了',
          enter:'进入',
        },
        {
          url:'../public/img/2.jpg',
          name:'前段开发电子书',
          outline:'午时快到了',
          enter:'进入',
        },
         {
          url:'../public/img/2.jpg',
          name:'前段开发电子书',
          outline:'午时快到了',
          enter:'进入',
        },
        {
          url:'../public/img/2.jpg',
          name:'前段开发电子书',
          outline:'午时快到了',
          enter:'进入',
        },
      ],
    })
  }
  async manual() {
    await this.ctx.render("manual.html",{
      logo:'手册',
      team:'团队介绍',
      xiaozhou:'晓舟报告',
      booklist:[
        {
          url:'../public/img/2.jpg',
          name:'前段开发电子书',
          outline:'午时快到了',
          enter:'进入',
        },
        {
          url:'../public/img/2.jpg',
          name:'前段开发电子书',
          outline:'午时快到了',
          enter:'进入',
        },
        {
          url:'../public/img/2.jpg',
          name:'前段开发电子书',
          outline:'午时快到了',
          enter:'进入',
        },
        {
          url:'../public/img/2.jpg',
          name:'前段开发电子书',
          outline:'午时快到了',
          enter:'进入',
        },
        {
          url:'../public/img/2.jpg',
          name:'前段开发电子书',
          outline:'午时快到了',
          enter:'进入',
        },
      ],
      itemlist:[
        {
          id:"1",
          url:'',
          word:'首页'
        },
        {
          id:"2",
          url:'',
          word:'手册'
        },
        {
          id:"3",
          url:'',
          word:'问答'
        },
        {
          id:"4",
          url:'',
          word:'我的'
        },
      ]
    })
  }
  async column() {
    await this.ctx.render("test.html",{
      a:'上海zoo',
      itemlist:[
        {
          id:"1",
          url:'',
          word:'首页'
        },
        {
          id:"2",
          url:'',
          word:'手册'
        },
        {
          id:"3",
          url:'',
          word:'问答'
        },
        {
          id:"4",
          url:'',
          word:'我的'
        },
      ]
    })
  }
  async my() {
    await this.ctx.render("test.html",{
      a:'马了顶大',
      itemlist:[
        {
          id:"1",
          url:'',
          word:'首页'
        },
        {
          id:"2",
          url:'',
          word:'手册'
        },
        {
          id:"3",
          url:'',
          word:'问答'
        },
        {
          id:"4",
          url:'',
          word:'我的'
        },
      ]
    })
  }
}

module.exports = HomeController;
